// components/Common/sapMenuData.js
import {
  BadgeCheck,
  BarChart3,
  Braces,
  Building2,
  Cloud,
  Code2,
  Database,
  Factory,
  FileText,
  Leaf,
  LineChart,
  Network,
  Package,
  ServerCog,
  ShieldCheck,
  Truck,
  UserRound,
  UsersRound,
  Wrench,
} from "lucide-react";

export const sapMenuSections = [
  {
    title: "SAP Functional",
    description: "Business & Process Oriented Solutions",
    Icon: UsersRound,
    items: [
      { name: "SAP FICO", link: "/sap-fico-course-in-pune", Icon: LineChart, color: "teal" },
      { name: "SAP Ariba", link: "/sap-ariba-course-in-pune", Icon: BadgeCheck, color: "yellow" },
      { name: "SAP MM", link: "/sap-mm-course-in-pune", Icon: Package, color: "orange" },
      { name: "SAP SD", link: "/sap-sd-course-in-pune", Icon: FileText, color: "cyan" },
      { name: "SAP HR/HCM", link: "/sap-hr-hcm-course-in-pune", Icon: UserRound, color: "violet" },
      { name: "SAP PP", link: "/sap-pp-course-in-pune", Icon: Factory, color: "purple" },
      { name: "SAP QM", link: "/sap-qm-course-in-pune", Icon: ShieldCheck, color: "blue" },
      { name: "SAP PM", link: "/sap-pm-course-in-pune", Icon: Wrench, color: "green" },
      { name: "SAP PS", link: "/sap-ps-course-in-pune", Icon: FileText, color: "pink" },
      { name: "SAP EWM", link: "/sap-ewm-course-in-pune", Icon: Truck, color: "orange" },
      { name: "SAP SCM", link: "/sap-scm-course-in-pune", Icon: Network, color: "sky" },
      { name: "SAP BTP", link: "/sap-btp-course-in-pune", Icon: Cloud, color: "blue" },
      { name: "SAP EHS", link: "/sap-ehs-course-in-pune", Icon: Leaf, color: "green" },
      { name: "SAP GRC", link: "/sap-grc-course-in-pune", Icon: ShieldCheck, color: "violet" },
      { name: "SAP IBP", link: "/sap-ibp-course-in-pune", Icon: BarChart3, color: "indigo" },
      { name: "SAP SUCCESSFACTOR", link: "/sap-successfactors-course-in-pune", Icon: UsersRound, color: "orange" },
    ],
  },
  {
    title: "SAP Technical",
    description: "Technology & Development Focused",
    Icon: Code2,
    items: [
      { name: "SAP ABAP", link: "/sap-abap-course-in-pune", Icon: Braces, color: "indigo" },
      { name: "SAP S/4 HANA", link: "/sap-s4-hana-course-in-pune", Icon: Building2, color: "blue", sapBadge: true },
      { name: "SAP BW/BI", link: "/sap-bwbi-course-in-pune", Icon: Database, color: "violet" },
      { name: "SAP BASIS", link: "/sap-basis-course-in-pune", Icon: ServerCog, color: "orange" },
    ],
  },
];
